"""added verified column to user table

Revision ID: 116f75e53fc1
Revises: 9e41b297836b
Create Date: 2025-06-01 17:14:28.244216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116f75e53fc1'
down_revision = '9e41b297836b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
