"""rating and save has timestamps'

Revision ID: 1732b54b5a53
Revises: cec258a0a644
Create Date: 2025-06-05 22:41:31.758624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1732b54b5a53'
down_revision = 'cec258a0a644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(timezone=True)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
