"""replies pls dont be null

Revision ID: 2408de2e6229
Revises: 4b80961fa11b
Create Date: 2025-06-14 13:28:43.738454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2408de2e6229'
down_revision = '4b80961fa11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('commenter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('comment_commenter_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['commenter_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_commenter_id_fkey', 'user', ['commenter_id'], ['id'])
        batch_op.alter_column('commenter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
