"""added user relationship to chatmessage as sender and receiver

Revision ID: 44cfa3d17d8b
Revises: 63b1dbd2dbed
Create Date: 2025-05-28 01:28:54.884548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cfa3d17d8b'
down_revision = '63b1dbd2dbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('room_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_code', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
