"""Initial migration

Revision ID: 4b80961fa11b
Revises: 
Create Date: 2025-06-14 12:50:08.375856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b80961fa11b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('commenter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('comment_commenter_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['commenter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_commenter_id_fkey', 'user', ['commenter_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('commenter_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
