"""added new column preview_path in note table

Revision ID: 5a8685a6470e
Revises: 819b8ef9bcea
Create Date: 2025-05-27 19:08:33.166524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8685a6470e'
down_revision = '819b8ef9bcea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('preview_path')

    # ### end Alembic commands ###
