"""added content for chatmessage

Revision ID: 63b1dbd2dbed
Revises: 5a8685a6470e
Create Date: 2025-05-28 01:11:21.451566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b1dbd2dbed'
down_revision = '5a8685a6470e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
