"""removed table noteimage

Revision ID: 9e41b297836b
Revises: 44cfa3d17d8b
Create Date: 2025-05-29 17:21:23.214312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e41b297836b'
down_revision = '44cfa3d17d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('note_id', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=300), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
