"""Add total_comments to note

Revision ID: bedc6ee1aa3c
Revises: fd7624156b40
Create Date: 2025-05-26 17:37:58.240941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bedc6ee1aa3c'
down_revision = 'fd7624156b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_comments', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('total_comments')

    # ### end Alembic commands ###
