"""added verified to user, b4 this accidentally added it to note

Revision ID: cec258a0a644
Revises: 116f75e53fc1
Create Date: 2025-06-01 17:29:53.107491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec258a0a644'
down_revision = '116f75e53fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('verified')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verified')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
