"""initial migration

Revision ID: dff6dceac62b
Revises: 
Create Date: 2025-06-14 15:33:59.545409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff6dceac62b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint('answer_question_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('commenter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('comment_commenter_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comment_note_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['commenter_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'note', ['note_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comment_vote', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_comment_vote', ['voter_id', 'comment_id'])

    with op.batch_alter_table('reply_vote', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_reply_vote', ['voter_id', 'reply_id'])

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('report_comment_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('report_reported_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('report_note_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'note', ['note_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['reported_by'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_note_id_fkey', 'note', ['note_id'], ['id'])
        batch_op.create_foreign_key('report_reported_by_fkey', 'user', ['reported_by'], ['id'])
        batch_op.create_foreign_key('report_comment_id_fkey', 'comment', ['comment_id'], ['id'])

    with op.batch_alter_table('reply_vote', schema=None) as batch_op:
        batch_op.drop_constraint('unique_reply_vote', type_='unique')

    with op.batch_alter_table('comment_vote', schema=None) as batch_op:
        batch_op.drop_constraint('unique_comment_vote', type_='unique')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_note_id_fkey', 'note', ['note_id'], ['id'])
        batch_op.create_foreign_key('comment_commenter_id_fkey', 'user', ['commenter_id'], ['id'])
        batch_op.alter_column('commenter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('answer_question_id_fkey', 'question', ['question_id'], ['id'])

    # ### end Alembic commands ###
