<<<<<<<< HEAD:migrations/versions/5e327ce5a65d_add_theme_preference_to_user_model.py
"""Add theme preference to User model

Revision ID: 5e327ce5a65d
Revises: 
Create Date: 2025-05-26 22:50:55.247109
========
"""user has theme preference column

Revision ID: ee57a690560f
Revises: 1732b54b5a53
Create Date: 2025-06-09 10:43:21.262830
>>>>>>>> f0563e43265a425dfe332da86fdc79798465cbdc:migrations/versions/ee57a690560f_user_has_theme_preference_column.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/5e327ce5a65d_add_theme_preference_to_user_model.py
revision = '5e327ce5a65d'
down_revision = None
========
revision = 'ee57a690560f'
down_revision = '1732b54b5a53'
>>>>>>>> f0563e43265a425dfe332da86fdc79798465cbdc:migrations/versions/ee57a690560f_user_has_theme_preference_column.py
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme_preference')

    # ### end Alembic commands ###
